os:
  - linux
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - source # build source branch only
before_install:
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo generate --force # generate static files
after_success:
  - git config --global user.name "Twittytop"
  - git config --global user.email "1690542111@qq.com"
  - sed -i "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy > /dev/null
